output: koral

directories:
  src: src
  obj: obj
  bin: bin
  include: []
  lib: []

ignore: [ include, lib ]

# Flags used for linking, leave None for empty
flags:
  error_flags: -Wall -Wunused-variable -Wextra -Wno-enum-compare -g -ggdb -fdiagnostics-color=always
  windows_lib_flags: None
  unix_lib_flags: None
  end_flags: None

compiler_version: g++
language_version: c++20

# Debug / Release
build_type: debug
